# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    paths:
      - '**/*src/**/*.java'
      - '**/*src/**/*.kt'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: alex-snapshots # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }}# location for the settings.xml file
          overwrite-settings: false

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "alex-snapshots", "url": "http://47.115.213.131:8080/repository/alex-snapshots/" }]'
          servers: '[{ "id": "alex-snapshots", "username": "githubPuber", "password": "meEFQ1$0tp!h%HNu" }]'

          mirrors: >
            [
              {
                "id": "alex-snapshots",
                "mirrorOf": "central-repos",
                "url": "http://47.115.213.131:8080/repository/alex-snapshots/",
                "blocked": "false"
              }
            ]

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests



      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -DskipTests
